name: Compile pgvector

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PGVECTOR_VERSION: 0.7.3

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Set up PostgreSQL and pgvector (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y postgresql-common
          sudo DEBIAN_FRONTEND=noninteractive /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y
          sudo DEBIAN_FRONTEND=noninteractive apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y postgresql-16 postgresql-server-dev-16
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y postgresql-16-pgvector

      - name: Set up PostgreSQL (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install postgresql@16
          echo "/usr/local/opt/postgresql@16/bin" >> $GITHUB_PATH

      - name: Set up PostgreSQL (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          choco install postgresql16 --params '/Password:postgres'
          echo "C:\Program Files\PostgreSQL\16\bin" >> $GITHUB_PATH
          echo "C:\Program Files\PostgreSQL\16" >> $GITHUB_PATH

      - name: Clone pgvector (macOS and Windows)
        if: runner.os != 'Linux'
        uses: actions/checkout@v3
        with:
          repository: "pgvector/pgvector"
          ref: "v${{ env.PGVECTOR_VERSION }}"

      - name: Compile pgvector (macOS)
        if: runner.os == 'macOS'
        run: |
          export PG_CONFIG="$(brew --prefix postgresql@16)/bin/pg_config"
          make
          sudo --preserve-env=PG_CONFIG make install

      - name: Set up Visual Studio and compile pgvector (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          set "PGROOT=C:\Program Files\PostgreSQL\16"
          nmake /F Makefile.win
          nmake /F Makefile.win install

      - name: Create artifact (Linux)
        if: runner.os == 'Linux'
        run: |
          mkdir -p pgvector-${{ runner.os }}-pg16/include/postgresql/16/server/extension/vector
          mkdir -p pgvector-${{ runner.os }}-pg16/lib/postgresql/16/lib/bitcode/vector/src
          mkdir -p pgvector-${{ runner.os }}-pg16/share/doc/postgresql-16-pgvector
          mkdir -p pgvector-${{ runner.os }}-pg16/share/postgresql/16/extension

          # Copy header files
          sudo cp /usr/include/postgresql/16/server/extension/vector/*.h pgvector-${{ runner.os }}-pg16/include/postgresql/16/server/extension/vector/

          # Copy bitcode files
          sudo cp /usr/lib/postgresql/16/lib/bitcode/vector.index.bc pgvector-${{ runner.os }}-pg16/lib/postgresql/16/lib/bitcode/
          sudo cp /usr/lib/postgresql/16/lib/bitcode/vector/src/*.bc pgvector-${{ runner.os }}-pg16/lib/postgresql/16/lib/bitcode/vector/src/

          # Copy shared object file
          sudo cp /usr/lib/postgresql/16/lib/vector.so pgvector-${{ runner.os }}-pg16/lib/postgresql/16/lib/

          # Copy extension files
          sudo cp /usr/share/postgresql/16/extension/vector*.sql pgvector-${{ runner.os }}-pg16/share/postgresql/16/extension/
          sudo cp /usr/share/postgresql/16/extension/vector.control pgvector-${{ runner.os }}-pg16/share/postgresql/16/extension/

          # Create zip archive
          zip -r pgvector-${{ runner.os }}-pg16.zip pgvector-${{ runner.os }}-pg16

      - name: Create artifact (macOS)
        if: runner.os == 'macOS'
        run: |
          # Create directory structure
          mkdir -p pgvector-${{ runner.os }}-pg16/lib/postgresql
          mkdir -p pgvector-${{ runner.os }}-pg16/share/postgresql@16/extension
          mkdir -p pgvector-${{ runner.os }}-pg16/include/postgresql/server/extension/vector

          # Copy shared library
          cp $(brew --prefix postgresql@16)/lib/postgresql/vector.dylib pgvector-${{ runner.os }}-pg16/lib/postgresql/

          # Copy extension files
          cp $(brew --prefix postgresql@16)/share/postgresql@16/extension/vector*.sql pgvector-${{ runner.os }}-pg16/share/postgresql@16/extension/
          cp $(brew --prefix postgresql@16)/share/postgresql@16/extension/vector.control pgvector-${{ runner.os }}-pg16/share/postgresql@16/extension/

          # Copy header files
          cp $(brew --prefix postgresql@16)/include/postgresql/server/extension/vector/*.h pgvector-${{ runner.os }}-pg16/include/postgresql/server/extension/vector/

          # Create a .so symlink for compatibility
          cp $(brew --prefix postgresql@16)/lib/postgresql/vector.dylib pgvector-${{ runner.os }}-pg16/lib/postgresql/vector.so

          # Create zip archive
          zip -r pgvector-${{ runner.os }}-pg16.zip pgvector-${{ runner.os }}-pg16

      - name: Create artifact (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          REM Create directory structure
          mkdir pgvector-${{ runner.os }}-pg16\lib
          mkdir pgvector-${{ runner.os }}-pg16\share\extension
          mkdir pgvector-${{ runner.os }}-pg16\include\postgresql\server\extension\vector

          REM Copy shared library
          copy "C:\Program Files\PostgreSQL\16\lib\vector.dll" pgvector-${{ runner.os }}-pg16\lib\

          REM Copy extension files
          copy "C:\Program Files\PostgreSQL\16\share\extension\vector*.sql" pgvector-${{ runner.os }}-pg16\share\extension\
          copy "C:\Program Files\PostgreSQL\16\share\extension\vector.control" pgvector-${{ runner.os }}-pg16\share\extension\

          REM Copy header files
          copy "C:\Program Files\PostgreSQL\16\include\server\extension\vector\halfvec.h" pgvector-${{ runner.os }}-pg16\include\postgresql\server\extension\vector\
          copy "C:\Program Files\PostgreSQL\16\include\server\extension\vector\sparsevec.h" pgvector-${{ runner.os }}-pg16\include\postgresql\server\extension\vector\
          copy "C:\Program Files\PostgreSQL\16\include\server\extension\vector\vector.h" pgvector-${{ runner.os }}-pg16\include\postgresql\server\extension\vector\

          REM Create zip archive
          7z a -tzip pgvector-${{ runner.os }}-pg16.zip pgvector-${{ runner.os }}-pg16

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: pgvector-${{ runner.os }}-pg16.zip
          name: v0.16.${{ github.run_number }}
          tag_name: v0.16.${{ github.run_number }}
          body: |
            pgvector v${{ env.PGVECTOR_VERSION }} for PostgreSQL 16
